### ISSUE TITLE
keeps running after throwing an error

### ISSUE THREAD

**Issue by v1rtl** [RocktimSaikia/github-feed-cli#10]
Even when the error is thrown, `feed` CLI keeps running

```
➜ feed -u=talentless_guy
⠼ Loading the feed...User not found! Please provide a valid github username.
RequestError [HttpError]: Not Found
    at /home/v1rtl/.pnpm-store/pnpm-global/4/node_modules/.pnpm/@octokit/request@5.4.10/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async module.exports (/home/v1rtl/.pnpm-store/pnpm-global/4/node_modules/.pnpm/github-feed-cli@1.3.1/node_modules/github-feed-cli/lib/index.js:108:24)
    at async /home/v1rtl/.pnpm-store/pnpm-global/4/node_modules/.pnpm/github-feed-cli@1.3.1/node_modules/github-feed-cli/bin/index.js:76:22 {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-length': '133',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Sun, 22 Nov 2020 11:51:18 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '9DC8:126C2:4987EF2:54A072A:5FBA50B6',
    'x-ratelimit-limit': '60',
    'x-ratelimit-remaining': '57',
    'x-ratelimit-reset': '1606046760',
    'x-ratelimit-used': '3',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/users/talentless_guy/received_events?page=1',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.0.9 octokit-core.js/3.2.1 Node.js/15.0.1 (linux; x64)'
    },
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/activity#list-events-received-by-the-authenticated-user'                                                                                                       
}
⠼ Loading the feed...⏎                                  
```

I think it should exit the program instead

**Comment by rocktimsaikia** [comment]
Right :+1:  I noticed it too. PRs are open if anyone wants to take it.
